Added unit test
FEC-Pina-Fraise-Frivolities/Atelier pull request #18
Opened 2023-05-09 21:26 UTC by MiladMoulayi

Created unit test for ProductData component of Overview module.

2023-05-10 00:46 UTC, gocodezhang requested changes
Given there are a few differences in server folder and related item module, **suggesting a group discussion before merging**

2023-05-10 00:46 UTC, gocodezhang commented on .eslintrc.js
> -    'airbnb/hooks',
Adding back airbnb/hooks

2023-05-10 00:46 UTC, gocodezhang commented on server/index.js
There seems to be quite a few differences in server/controllers and index.js files

2023-05-10 00:46 UTC, gocodezhang commented on client/src/components/related-items-and-outfit/index.jsx
There seems to be a few changes in related items module

2023-05-10 23:35 UTC, HeyMaximus approved these changes

2023-05-11 16:42 UTC, gocodezhang approved these changes

2023-05-11 19:25 UTC, merged